### ISSUE TITLE
INFRASTRUCTURE_FACTORY vs PERSISTENCE_MODULE problems

### ISSUE THREAD

**Issue by avilaton** [pyeventsourcing/eventsourcing-sqlalchemy#3]
During an exploratory test
```
    os.environ['INFRASTRUCTURE_FACTORY'] = 'eventsourcing_sqlalchemy.factory:Factory'
    os.environ["SQLALCHEMY_URL"] = "sqlite:///wtf.sqlite3"
```
and running a demo application as described in the readme, we see a wtf.sqlite3 DB file created correctly while
```
    os.environ["PERSISTENCE_MODULE"] = "eventsourcing_sqlalchemy"
    os.environ["SQLALCHEMY_URL"] = "sqlite:///wtf.sqlite3"
```
does not cause the same effect.
Any ideas what could be the root cause?
Also we noticed that
```
    os.environ["PERSISTENCE_MODULE"] = "any_random_string"
```
does not make the application crash, while changes to INFRASTRUCTURE_FACTORY are validated right away.

**Comment by johnbywater** [comment]
Thanks for raising this! I will look into it now...

**Comment by johnbywater** [comment]
The difference is the `PERSISTENCE_MODULE` name will supported in the next release of the eventsourcing library (v9.2) but this hasn't yet been released. A new version of this package will be released that includes this change soon. The README file on the main branch of this repo represents the new unreleased version. The stable versions of these packages don't support this setting, and the docs for these stable versions don't mention this setting. See:

- https://github.com/pyeventsourcing/eventsourcing/tree/9.1
- https://github.com/pyeventsourcing/eventsourcing-sqlalchemy/tree/0.1
- https://pypi.org/project/eventsourcing-sqlalchemy/0.1.1/
- https://eventsourcing.readthedocs.io/en/v9.1.9/topics/application.html#configuring-persistence

The new versions will be released very soon!

**Comment by avilaton** [comment]
Thanks for clarifying that. I think the readme on the main branch should be something one can trust to work with, specially given the fact that it is the only source of documentation for eventsourcing_sqlalchemy. I would recommend that unreleased changes should be on a separate branch, but it is matter of taste. This took me a while to figure out and we wouldn't want people trying the package out to be mislead.
Thanks again!

**Comment by johnbywater** [comment]
Yes, I appreciate this view. It used to be that I generally had the 'main' branch as the stable branch, with a dev branch that had unreleased changes. But it seems more common these days for the main branch to be the "latest" and then to have release branches which are effectively the stable branches. But I don't have any data about which is actually more common. I'm sorry for the misdirection. Thanks again for raising this issue, and also for your interest in this package. If you have any need for further assistance, or have any other questions or issues, please don't hesitate to raise them. Good luck!

**Comment by albertmenglongli** [comment]
Thanks @johnbywater , I think it's my sqlalchemy version issue, you can close this issue.
