### ISSUE TITLE
SqlAlchemy 2.0 compatibility

### ISSUE THREAD

**Issue by pndiku** [pyeventsourcing/eventsourcing-sqlalchemy#6]
Is there a plan to make this not require SQLAlchemy 1.4? Is there breakage in v2.0 that prevents the library from working?

**Comment by johnbywater** [comment]
Hi @pndiku, sorry for the long delay in responding. I was having an extended summer break, but I'm back now.

After you opened this issue, @Chris927 submitted #5 which implements this. I'm looking into this now.

**Comment by johnbywater** [comment]
#5 was merged. And I just released the changes as [version 0.4](https://pypi.org/project/eventsourcing-sqlalchemy/0.4/). So there is now support for SQLAlchemy 2.0.
